spring:
    application.name: kafka-stream-push-sample

    cloud:
        stream:
            default:
                default-binder: local-kafka

            binders:
                # Kafka 별 세팅
                local-kafka:
                    type: kafka
                    environment:
                        spring.cloud.stream.kafka.binder.broker: localhost:9092

            bindings:
                # producer
                basicProducer-out-0:
                    binder: local-kafka
                    destination: chat # 토픽
                    content-type: application/json


    # H2 Database 설정
    datasource:
        driver-class-name: org.h2.Driver
        url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
        username: username        # H2 DB 접속 ID (사용자 지정)
        password: password        # H2 DB 접속 PW (사용자 지정)

        # JPA 설정
        jpa:
            database-platform: org.hibernate.dialect.H2Dialect
            hibernate:
                ddl-auto: create        # DB 초기화 전략 (none, create, create-drop, update, validate)
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.H2Dialect
                    format_sql: true      # 쿼리 로그 포맷 (정렬)
                    show_sql: true        # 쿼리 로그 출력

server:
    shutdown: graceful


